[package]
name = "reactor_rs"
version = "0.0.1"
authors = ["Jeffsky <jjeffcaii@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
futures = "0.1.29"

[dev-dependencies]
env_logger = "0.6.2"
rand = "0.7.0"

